name		  	  "mysql-connector"
maintainer        "Thirdwave, LLC"
maintainer_email  "support@thirdwavellc.com"
license           "Apache 2.0"
description       "Installs and configures MySQL Connector"
version           "0.3.0"
